version: "3.6"

services:
 test:
  build: ./test
  user: root
  volumes:
    - "./:/root/.minetest/worlds/world/worldmods/monitoring/"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
